### ISSUE TITLE
Pen - Draw dashed line failed

### ISSUE THREAD

**Issue by ThomasFischer1** [ZEISS-PiWeb/PiWeb-Customplot#1]
When you draw a dashed line, there is such strange behavior.

The normal line is drawn correctly.
The dashed line types are all drawn incorrectly, and one type is even not drawn at all.

See the pictures below
![PenDashedLineType1](https://user-images.githubusercontent.com/61225783/99501503-24803e80-297c-11eb-97de-a325a392e70b.png)
![PenDashedLineType2](https://user-images.githubusercontent.com/61225783/99501440-0a466080-297c-11eb-9283-3c7190f15523.png)
![PenDashedLineType3](https://user-images.githubusercontent.com/61225783/99501445-0b778d80-297c-11eb-9e1f-8ef1316663df.png)
![PenDashedLineType4](https://user-images.githubusercontent.com/61225783/99501446-0b778d80-297c-11eb-82c8-e9a5865d2a8d.png)
![PenDashedLineType5](https://user-images.githubusercontent.com/61225783/99501442-0adef700-297c-11eb-8098-9875bc61e99e.png)

**Comment by Schnjan** [comment]
This behavior is caused by our default value `flat` for the dash cap property of the pen. The default value for WPF pens is `square`. 

The default dash type 'dots' is defined as `[0, 2]`, which means, that the length of the dot is 0, but it's extended by two dash caps, which makes it appear as length 1. That's some very strange and confusing design decision by microsoft...

A quick workaround is to set all pen dash caps explicitly to `square`. Meanwhile, we'll discuss whether it's a good idea to change the default behavior of our plots.

**Comment by ThomasFischer1** [comment]
Thanks the workaround works perfect.

**Comment by Schnjan** [comment]
The behavior is going to change with PiWeb 7.8. Pens that are specified in PiWeb will have a `square` dash cap and a `miter` line join. This might change the appearance of existing plots.
